spring.application.name=sd-persistencia
spring.datasource.url=jdbc:postgresql://localhost:5432/votacao_db
spring.datasource.username=postgres
spring.datasource.password=19e170
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# Configurações de Resiliência (Resilience4j)
# ==========================================
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=false
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold=2s
resilience4j.circuitbreaker.configs.default.slowCallRateThreshold=50
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

resilience4j.timelimiter.configs.default.timeoutDuration=3s
resilience4j.timelimiter.configs.default.cancelRunningFuture=true

# Aplicar ao nosso backend
resilience4j.circuitbreaker.instances.bancoDados.baseConfig=default
resilience4j.timelimiter.instances.bancoDados.baseConfig=default

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always