server {
    listen       80;
    server_name  localhost;

    # Serve o Frontend estático
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Proxy reverso: tudo que for para /api, envia pro backend usando o DNS interno do Kubernetes
    location /api/ {
        proxy_pass http://api-service:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
