apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: api-pod-kill-schedule
  namespace: default
spec:
  schedule: '@every 60s'
  type: 'PodChaos'
  historyLimit: 2
  concurrencyPolicy: 'Forbid'
  podChaos:
    action: pod-kill
    mode: one
    selector:
      labelSelectors:
        app: api-votacao
